server:
  address: 0.0.0.0
  port: 8081

spring:
  datasource:
    url: "jdbc:h2:mem:test"
    username: "test"
    password: "test"
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: update
  h2:
    console:
      enabled: true
      path: /h2